.EH ''''
.OH ''''
.EF ''''
.OF ''''
.ps 11
.nr PS 11
\&
.sp 10
.ce 6
\s+6\fBXwchar Libraray\fP\s-6
.bp
\&
.sp 5
.ce 6
\s+2\fBIntroduction\fP\s-2
.sp 6
.PP
This section descibes the Xwchar library which supports the internal
processing encoding, i.e., wide character encoding.
This implemenation of wchar encoding is based on:
.IP
Information Processing -- Programming Language C 
.br
ADDENDUM 3 Multibyte Support Extensions
.br
SC22/WG14/N145R 1991-04-22
.IP
ISO DIS 10646(UCS), 4 November 1990.
