#!/bin/csh
if ($#argv >= 1) then
   setenv XAPPLRESDIR ${1}ari
else
   setenv XAPPLRESDIR ./
   cd Ari
endif
if (-e Ari) then
    echo ============= Testing Ari =============
    foreach example (${XAPPLRESDIR}A[0-9][0-9]_*)
	echo Ari $example:t
	Ari $example:t
    end
endif
if ($#argv == 0 ) then
   cd ..
endif

