#!/bin/csh
if ($#argv >= 1) then
   setenv XAPPLRESDIR $1
else
   setenv XAPPLRESDIR ./
   cd DemosAthena
endif
if (-e Athena ) then
    echo ============= Testing Athena =============
    Athena SD 
endif
if (-e MDathena) then
    echo ============= Testing MDathena =============
    MDathena MD
endif
if ($#argv == 0 ) then
   cd ..
endif
