#!/bin/csh
if ($#argv >= 1) then
   setenv XAPPLRESDIR ${1}ori
else
   setenv XAPPLRESDIR ./
   cd Ori
endif
if (-e Ori) then
    echo ============= Testing Ori =============
    foreach example (${XAPPLRESDIR}O[0-9][0-9]_*)
	echo Ori $example:t
	Ori $example:t
    end
endif
if ($#argv == 0 ) then
   cd ..
endif

