#!/bin/csh
if ($#argv >= 1) then
   setenv XAPPLRESDIR $1
else
   setenv XAPPLRESDIR ./
   cd DemosCornell
endif
if (-e MDcornell) then
    echo ============= Testing MDcornell =============
    MDcornell MD
endif
if ($#argv == 0 ) then
   cd ..
endif
