#!/bin/csh -f
## ###################################################################### ##
##         Copyright IBM Corporation 1988,1991 - All Rights Reserved      ##
##        For full copyright information see:'andrew/config/COPYRITE'     ##
## ###################################################################### ##

set TOP=$1
set DESTDIR=$2
set INSTALL=$3
set FLAGS="$4 $5 $6"
set FILE=$7
set DEST=$8
set PWD=`pwd | sed -e 's;/afs.*itcobjects/;;'`

$INSTALL $FLAGS $FILE $DEST
set STAT=$status
if ($STAT == 0) then
	if (-d $DEST) then
		echo "|`date`|$PWD/$FILE|$DEST/$FILE|" | sed -e 's;//;/;g' >>& $DESTDIR/doc/InstallLog
	else
		echo "|`date`|$PWD/$FILE|$DEST|" >>& $DESTDIR/doc/InstallLog
	endif
endif
exit ($STAT)





