/* $XConsortium: test_ss.h,v 5.1 91/02/16 09:32:40 rws Exp $ */
/***********************************************************
Copyright 1989,1990, 1991 by Sun Microsystems, Inc. and the X Consortium.

                        All Rights Reserved

Permission to use, copy, modify, and distribute this software and its 
documentation for any purpose and without fee is hereby granted, 
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in 
supporting documentation, and that the names of Sun Microsystems,
the X Consortium, and MIT not be used in advertising or publicity 
pertaining to distribution of the software without specific, written 
prior permission.  

SUN MICROSYSTEMS DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, 
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT 
SHALL SUN MICROSYSTEMS BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL 
DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
SOFTWARE.

******************************************************************/

static char *oc_names[] = {
	"Nil",
	"Polyline 3",
	"Polyline",
	"PolyMarker 3",
	"PolyMarker",
	"Text 3",
	"Text",
	"Annotation Text Relative 3",
	"Annotation Text Relative",
	"Fill Area 3",
	"Fill Area",
	"Fill Area Set 3",
	"Fill Area Set",
	"Cell Array 3",
	"Cell Array",
	"Generalized Drawing Primitive 3",
	"Generalized Drawing Primitive",
	"Polyline Index",
	"Polymarker Index",
	"Text Index",
	"Interior Index",
	"Edge Index",
	"Line Type",
	"Line Width Scale Factor",
	"Polyline Colour Index",
	"Marker Type",
	"Marker Size Scale Factor",
	"Marker Colour Index",
	"Text Font",
	"Text Precision",
	"Character Expansion Factor",
	"Character Spacing",
	"Text Colour Index",
	"Character Height",
	"Character Up Vector",
	"Text Path",
	"Text Alignment",
	"Annotation Text Character Height",
	"Annotation Text Character Up Vector",
	"Annotation Text Path",
	"Annotation Text Alignment",
	"Annotation Style",
	"Interior Style",
	"Interior Style Index",
	"Interior Style Colour Index",
	"Edge Flag",
	"Edge Type",
	"Edge Width Scale Factor",
	"Edge Colour Index",
	"Pattern Size",
	"Pattern Reference Point and Vectors",
	"Pattern Reference Point",
	"Add Names To Set",
	"Remove Names From Set",
	"Individual Asf",
	"Hlhsr Identifier",
	"Local Modelling Transformation 3",
	"Local Modelling Transformation",
	"Global Modelling Transformation 3",
	"Global Modelling Transformation",
	"Modelling Clipping Volume 3",
	"Modelling Clipping Volume",
	"Modelling Clipping Indicator",
	"Restore Modelling Clipping Volume",
	"View Index",
	"Execute Structure",
	"Label",
	"Application Data",
	"Generalize Structure Element",
	"Pick ID",
	"Polyline Set 3 With Data",
	"Fill Area 3 With Data",
	"Fill Area Set With Data",
	"Triangle Strip 3 With Data",
	"Quad Mesh 3 With Data",
	"Polyhedron 3 With Data",
	"NURB Curve",
	"NURB Surface",
	"Extended Cell Array 3",
	"Text Colour",
	"PolyMarker Colour",
	"Edge Colour",
	"Polyline Colour",
	"Curve Approximation Criteria",
	"Polyline Shading Method",
	"Interior Colour",
	"Back Interior Colour",
	"Back Interior Style",
	"Back Interior Style Index",
	"Area Properties",
	"Back Area Properties",
	"Interior Shading Method",
	"Back Interior Shading Method",
	"Interior Reflectance Equation",
	"Back Interior Reflectance Equation",
	"Surface Approximation Criteria",
	"Trim Curve Approximation Criteria",
	"Face Distinguishing Mode",
	"Face Culling Mode",
	"Light Source State",
	"Depth Cue Index",
	"Colour Mapping Index",
	"Rendering Colour Model"
};
