.\" $Header: XpexTransform.man,v 2.5 91/09/11 16:02:33 sinyaw Exp $
.\"
.\"
.\" Copyright 1991 by Sony Microsystems Company, San Jose, California
.\" 
.\"                   All Rights Reserved
.\"
.\" Permission to use, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted,
.\" provided that the above copyright notice appear in all copies and
.\" that both that copyright notice and this permission notice appear
.\" in supporting documentation, and that the name of Sony not be used
.\" in advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\"
.\" SONY DISCLAIMS ANY AND ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
.\" INCLUDING ALL EXPRESS WARRANTIES AND ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS, FOR A PARTICULAR PURPOSE. IN NO EVENT
.\" SHALL SONY BE LIABLE FOR ANY DAMAGES OF ANY KIND, INCLUDING BUT NOT
.\" LIMITED TO SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES RESULTING FROM
.\" LOSS OF USE, DATA OR LOSS OF ANY PAST, PRESENT, OR PROSPECTIVE PROFITS,
.\" WHETHER IN AN ACTION OF CONTRACT, NEGLIENCE OR OTHER TORTIOUS ACTION, 
.\" ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS 
.\" SOFTWARE.
.\"
.\" 
.TH XpexTransform 3PEX "$Revision: 2.5 $" "Sony Microsystems"
.AT
.SH "Name"
XpexTransformPoint \- apply a 3D transformation matrix to a specified 3D
point
.sp
XpexTransformPoint2D \- apply a 2D transformation matrix to a specified 2D
point
.SH "Synopsis"
.nf
void XpexTransformPoint(point, transformation_matrix, transformed_point)
.br
	XpexCoord3D *point; 
.br
	XpexMatrix transformation_matrix; 
.br
	XpexCoord3D *transformed_point; /* RETURN */
.sp
void XpexTransformPoint2D(point, transformation_matrix, transformed_point)
.br
	XpexCoord2D *point;
.br
	XpexMatrix3X3 transformation_matrix;
.br
	XpexCoord2D *transformed_point;  /* RETURN */
.fi
.SH "Arguments"
.IP \fIpoint\fP 1i
To be added
.IP \fItransformation_matrix\fP 1i
To be added
.IP \fItransformed_point\fP 1i
To be added
.SH "Description"
Refer to the description in PEX-SI PHIGS Reference Manual.
.SH "Structures"
typedef struct {
.br
	XpexFloat  x;
.br
	XpexFloat  y;
.br
	XpexFloat  z;
.br
} XpexCoord3D;
.sp
typedef struct {
.br
	XpexFloat  x;
.br
	XpexFloat  y;
.br
} XpexCoord2D;
.SH "Errors"
None
.SH "Related Commands"
To be added
