.\" $Header: XpexSetAtextStyle.man,v 2.5 91/09/11 16:02:13 sinyaw Exp $
.\"
.\"
.\" Copyright 1991 by Sony Microsystems Company, San Jose, California
.\" 
.\"                   All Rights Reserved
.\"
.\" Permission to use, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted,
.\" provided that the above copyright notice appear in all copies and
.\" that both that copyright notice and this permission notice appear
.\" in supporting documentation, and that the name of Sony not be used
.\" in advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\"
.\" SONY DISCLAIMS ANY AND ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
.\" INCLUDING ALL EXPRESS WARRANTIES AND ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS, FOR A PARTICULAR PURPOSE. IN NO EVENT
.\" SHALL SONY BE LIABLE FOR ANY DAMAGES OF ANY KIND, INCLUDING BUT NOT
.\" LIMITED TO SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES RESULTING FROM
.\" LOSS OF USE, DATA OR LOSS OF ANY PAST, PRESENT, OR PROSPECTIVE PROFITS,
.\" WHETHER IN AN ACTION OF CONTRACT, NEGLIENCE OR OTHER TORTIOUS ACTION, 
.\" ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS 
.\" SOFTWARE.
.\"
.\" 
.\"
.\"
.\"
.TH XpexSetAtextStyle 3PEX "$Revision: 2.5 $" "Sony Microsystems"
.AT
.SH "Name"
XpexSetAtextStyle \- set annotation text style
.sp
XpexSetAtextHeight \- set annotation text height
.sp
XpexSetAtextPath \- set annotation text path
.sp
XpexSetAtextAlignment \- set annotation text alignment
.sp
XpexSetAtextUpVector \-
.SH "Synopsis"
.nf
void XpexSetAtextStyle(dpy, style)
.br
	Display *dpy;
.br
	XpexEnumTypeIndex style;
.sp
void XpexSetAtextHeight(dpy, height)
.br
	Display *dpy;
.br
	XpexFloat height;
.sp
void XpexSetAtextPath(dpy, path)
.br
	Display *dpy;
.br
	XpexTextPath path;
.sp
void XpexSetAtextAlignment(dpy, vertical, horizontal)
.br
	Display *dpy;
.br
	XpexTextValignment vertical;
.br
	XpexTextHalignment horizontal;
.sp
void XpexSetAtextUpVector(dpy, up)
.br
	Display *dpy;
.br
	XpexVector2D *up;
.fi
.SH "Arguments"
.IP \fIdpy\fP 1i
Specifies a pointer to the Display structure; 
returned from XOpenDisplay.
.IP \fIstyle\fP 1i
To be added 
.IP \fIheight\fP 1i
To be added 
.IP \fIpath\fP 1i
To be added 
.IP \fIvertical\fP 1i
To be added 
.IP \fIhorizontal\fP 1i
To be added 
.IP \fIup\fP 1i
To be added 
.SH "Description"
To be added 
.SH "Structures"
To be added 
.SH "Errors"
Structure, Renderer, FloatingPointFormat, OutputCommand, Value
.SH "Related Commands" 
To be added 
