.\" $Header: XpexAddToNameSet.man,v 2.3 91/09/11 16:04:00 sinyaw Exp $
.\"
.\"
.\" Copyright 1991 by Sony Microsystems Company, San Jose, California
.\" 
.\"                   All Rights Reserved
.\"
.\" Permission to use, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted,
.\" provided that the above copyright notice appear in all copies and
.\" that both that copyright notice and this permission notice appear
.\" in supporting documentation, and that the name of Sony not be used
.\" in advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\"
.\" SONY DISCLAIMS ANY AND ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
.\" INCLUDING ALL EXPRESS WARRANTIES AND ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS, FOR A PARTICULAR PURPOSE. IN NO EVENT
.\" SHALL SONY BE LIABLE FOR ANY DAMAGES OF ANY KIND, INCLUDING BUT NOT
.\" LIMITED TO SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES RESULTING FROM
.\" LOSS OF USE, DATA OR LOSS OF ANY PAST, PRESENT, OR PROSPECTIVE PROFITS,
.\" WHETHER IN AN ACTION OF CONTRACT, NEGLIENCE OR OTHER TORTIOUS ACTION, 
.\" ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS 
.\" SOFTWARE.
.\"
.\"
.TH XpexAddToNameSet 3PEX "$Revision: 2.3 $" "Sony Microsystems"
.AT
.SH "Name"
XpexAddToNameSet \-
.sp
XpexRemoveFromNameSet \-
.sp
XpexSetPickId \-
.sp
XpexSetHlhsrId \-
.SH "Synopsis"
.nf
void XpexAddToNameSet(dpy, names, count)
.br
	Display *\fIdpy\fP;
.br
	XpexName *\fInames\fP;
.br
	int \fIcount\fP;
.sp
void XpexRemoveFromNameSet(dpy, names, count)
.br
	Display *\fIdpy\fP;
.br
	XpexName *\fInames\fP;
.br
	int \fIcount\fP;
.sp
void XpexSetPickId(dpy, pick_id)
.br
	Display *\fIdpy\fP;
.br
	int \fIpick_id\fP;
.sp
void XpexSetHlhsrId(dpy, hlhsr_id)
.br
	Display *\fIdpy\fP;
.br
	int \fIhlhsr_id\fP;
.fi
.SH "Arguments"
.IP \fIdpy\fP 1i
Specifies a pointer to the Display structure; 
returned from XOpenDisplay.
.IP \fInames\fP 1i
[ To be added ]
.IP \fIcount\fP 1i
[ To be added ]
.IP \fIpick_id\fP 1i
[ To be added ]
.IP \fIhlhsr_id\fP 1i
[ To be added ]
.SH "Description"
When processed by a renderer, \fIXpexAddToNameSet\fP will add 
names to the renderer's name set.
.SH "Structures"
None
.SH "Errors"
Structure, Renderer, FloatingPointFormat, OutputCommand, Value
.SH "Related Commands"
[ To be added ]
