.\" $Header: XpexSetSurfaceColor.man,v 2.5 91/09/11 16:03:43 sinyaw Exp $
.\"
.\"
.\" Copyright 1991 by Sony Microsystems Company, San Jose, California
.\" 
.\"                   All Rights Reserved
.\"
.\" Permission to use, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted,
.\" provided that the above copyright notice appear in all copies and
.\" that both that copyright notice and this permission notice appear
.\" in supporting documentation, and that the name of Sony not be used
.\" in advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\"
.\" SONY DISCLAIMS ANY AND ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
.\" INCLUDING ALL EXPRESS WARRANTIES AND ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS, FOR A PARTICULAR PURPOSE. IN NO EVENT
.\" SHALL SONY BE LIABLE FOR ANY DAMAGES OF ANY KIND, INCLUDING BUT NOT
.\" LIMITED TO SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES RESULTING FROM
.\" LOSS OF USE, DATA OR LOSS OF ANY PAST, PRESENT, OR PROSPECTIVE PROFITS,
.\" WHETHER IN AN ACTION OF CONTRACT, NEGLIENCE OR OTHER TORTIOUS ACTION, 
.\" ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS 
.\" SOFTWARE.
.\"
.\" 
.TH XpexSetSurfaceColor 3PEX "$Revision: 2.5 $" "Sony Microsystems"
.AT
.SH "Name"
XpexSetSurfaceColor \-
.sp
XpexSetSurfaceColorIndex \-
.sp
XpexSetReflectionAttributes \-
.sp
XpexSetReflectionModel \-
.sp
XpexSetSurfaceInterpMethod \-
.sp
XpexSetSurfaceApproxMethod \-
.sp
XpexSetCullingMode \-
.sp
XpexSetDistinguishFlag \-
.SH "Synopsis"
.nf
void XpexSetSurfaceColor(dpy, color)
.br
	Display *dpy;
.br
	XpexColor *color;
.sp
void XpexSetSurfaceColorIndex(dpy, color_index)
.br
	Display *dpy;
.br
	XpexTableIndex color_index;
.sp
void XpexSetReflectionAttributes(dpy, reflection_attr)
.br
	Display *dpy;
.br
	XpexReflectionAttr *reflection_attr;
.sp
void XpexSetReflectionModel(dpy, model)
.br
	Display *dpy;
.br
	XpexEnumTypeIndex model;
.sp
void XpexSetSurfaceInterpMethod(dpy, method)
.br
	Display *dpy;
.br
	XpexEnumTypeIndex method;
.sp
void XpexSetSurfaceApproxMethod(dpy, approx_method, u_tolerance, v_tolerance)
.br
	Display *dpy;
.br
	XpexEnumTypeIndex approx_method;
.br
	XpexFloat u_tolerance;
.br
	XpexFloat v_tolerance;
.sp
void XpexSetCullingMode(dpy, mode)
.br
	Display *dpy;
.br
	XpexCullMode mode;
.sp
void XpexSetDistinguishFlag(dpy, dist_flag)
.br
	Display *dpy;
.br
	XpexSwitch dist_flag;
.fi
.SH "Arguments"
.IP \fIdpy\fP 1i
Specifies a pointer to the Display structure;
returned from XOpenDisplay.
.IP \fIcolor\fP 1i
To be added 
.IP \fIcolor_index\fP 1i
To be added 
.IP \fIreflection_attr\fP 1i
To be added 
.IP \fImodel\fP 1i
To be added
.IP \fImethod\fP 1i
To be added
.IP \fIapprox_method\fP 1i
To be added
.IP \fIu_tolerance\fP 1i
To be added
.IP \fIv_tolerance\fP 1i
To be added
.IP \fImode\fP 1i
To be added
.IP \fIdist_flag\fP 1i
To be added
.SH "Description"
Refer to the PEX Protocol Specification Document, Section 3.
.SH "Structures"
To be added
.SH "Errors"
Structure, Renderer, FloatingPointFormat, OutputCommand, Value
.SH "Related Commands"
To be added 
