.\" $Header: XpexFillArea.man,v 2.4 91/09/11 16:02:43 sinyaw Exp $
.\"
.\"
.\" Copyright 1991 by Sony Microsystems Company, San Jose, California
.\" 
.\"                   All Rights Reserved
.\"
.\" Permission to use, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted,
.\" provided that the above copyright notice appear in all copies and
.\" that both that copyright notice and this permission notice appear
.\" in supporting documentation, and that the name of Sony not be used
.\" in advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\"
.\" SONY DISCLAIMS ANY AND ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
.\" INCLUDING ALL EXPRESS WARRANTIES AND ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS, FOR A PARTICULAR PURPOSE. IN NO EVENT
.\" SHALL SONY BE LIABLE FOR ANY DAMAGES OF ANY KIND, INCLUDING BUT NOT
.\" LIMITED TO SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES RESULTING FROM
.\" LOSS OF USE, DATA OR LOSS OF ANY PAST, PRESENT, OR PROSPECTIVE PROFITS,
.\" WHETHER IN AN ACTION OF CONTRACT, NEGLIENCE OR OTHER TORTIOUS ACTION, 
.\" ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS 
.\" SOFTWARE.
.\"
.\" 
.TH XpexFillArea 3PEX "$Revision: 2.4 $" "Sony Microsystems"
.AT
.SH "Name"
XpexFillArea, XpexFillArea2D \-
.SH "Synopsis"
.nf
void XpexFillArea(dpy, shape, ignoreEdges, points, numPoints)
.br
	Display  *dpy;
.br
	XpexShape  shape;
.br
	XpexSwitch  ignoreEdges;
.br
	XpexCoord3D  *points;
.br
	int  numPoints;
.sp
void XpexFillArea2D(dpy, shape, ignoreEdges, points, numPoints)
.br
	Display  *dpy;
.br
	XpexShape  shape;
.br
	XpexSwitch  ignoreEdges;
.br
	XpexCoord2D  *points;
.br
	int  numPoints;
.fi
.SH "Arguments"
.IP \fIdpy\fP 1i
Specifies a pointer to the Display structure;
returned from XOpenDisplay.
.IP \fIshape\fP 1i
To be added 
.IP \fIignoreEdges\fP 1i
To be added 
.IP \fIpoints\fP 1i
Specifies an array of points.
.IP \fInumPoints\fP 1i
Specifies the number of points in the array.
.SH "Description"
Refer to the PEX Protocol Specification Document, Section 3.
.SH "Structures"
To be added 
.SH "Errors"
BadStructure, 
BadRenderer, 
BadFloatingPointFormat, 
BadOutputCommand, 
BadValue.
.SH "Related Commands"
XpexRenderOutputCmds, XpexStoreOutputCmds.
.br
