.\" $Header: XpexGetTableInfo.man,v 2.6 91/09/11 16:04:10 sinyaw Exp $
.\"
.\"
.\" Copyright 1991 by Sony Microsystems Company, San Jose, California
.\" 
.\"                   All Rights Reserved
.\"
.\" Permission to use, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted,
.\" provided that the above copyright notice appear in all copies and
.\" that both that copyright notice and this permission notice appear
.\" in supporting documentation, and that the name of Sony not be used
.\" in advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\"
.\" SONY DISCLAIMS ANY AND ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
.\" INCLUDING ALL EXPRESS WARRANTIES AND ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS, FOR A PARTICULAR PURPOSE. IN NO EVENT
.\" SHALL SONY BE LIABLE FOR ANY DAMAGES OF ANY KIND, INCLUDING BUT NOT
.\" LIMITED TO SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES RESULTING FROM
.\" LOSS OF USE, DATA OR LOSS OF ANY PAST, PRESENT, OR PROSPECTIVE PROFITS,
.\" WHETHER IN AN ACTION OF CONTRACT, NEGLIENCE OR OTHER TORTIOUS ACTION, 
.\" ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS 
.\" SOFTWARE.
.\"
.\" 
.TH XpexGetTableInfo 3PEX "$Revision: 2.6 $" "Sony Microsystems" 
.AT
.SH "Name"
XpexGetTableInfo, XpexGetDefinedIndices \- 
Inquire lookup table attributes
.SH "Synopsis"
.nf
Status XpexGetTableInfo(dpy, drawable, table_type, table_info)
.br
	Display *\fIdpy\fP;
.br
	Drawable \fIdrawable\fP;
.br
	XpexTableType \fItable_type\fP;
.br
	XpexTableInfo *\fItable_info\fP; /* RETURN */
.sp
Status XpexGetDefinedIndices(dpy, lut_id, indices, count)
.br
	Display *\fIdpy\fP;
.br
	XpexLookupTable \fIlut_id\fP;
.br
	XpexTableIndex **\fIindices\fP; /* RETURN */
.br
	int *\fIcount\fP; /* RETURN */
.fi
.SH "Arguments"
.IP \fIdisplay\fP 1i
Specifies a pointer to the Display structure;
returned from XOpenDisplay.
.IP \fIdrawable\fP 1i
Specifies the drawable.
.IP \fItable_type\fP  1i
To be added 
.IP \fItable_info\fP  1i
To be added 
.IP \fIlut_id\fP  1i
To be added 
.IP \fIcount\fP  1i
To be added 
.SH "Description"
Refer to PEX Protocol Specification Document, Section 4.2.
.SH "Structures"
typedef struct {
.br
	int definable_entries;
.br
	int num_predefined;
.br
	XpexTableIndex predefined_min;
.br
	XpexTableIndex predefined_max;
.br
} XpexTableInfo;
.SH "Errors"
BadDrawable, BadValue
.SH "Related Commands"
To be added 
