.\"
.\" $Header: pexlsfonts.man,v 1.5 91/09/11 17:40:28 sinyaw Exp $
.\"
.\"
.\"
.\" Copyright 1991 by Sony Microsystems Company, San Jose, California
.\" 
.\"                   All Rights Reserved
.\"
.\" Permission to use, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted,
.\" provided that the above copyright notice appear in all copies and
.\" that both that copyright notice and this permission notice appear
.\" in supporting documentation, and that the name of Sony not be used
.\" in advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\"
.\" SONY DISCLAIMS ANY AND ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
.\" INCLUDING ALL EXPRESS WARRANTIES AND ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS, FOR A PARTICULAR PURPOSE. IN NO EVENT
.\" SHALL SONY BE LIABLE FOR ANY DAMAGES OF ANY KIND, INCLUDING BUT NOT
.\" LIMITED TO SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES RESULTING FROM
.\" LOSS OF USE, DATA OR LOSS OF ANY PAST, PRESENT, OR PROSPECTIVE PROFITS,
.\" WHETHER IN AN ACTION OF CONTRACT, NEGLIENCE OR OTHER TORTIOUS ACTION, 
.\" ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS 
.\" SOFTWARE.
.\"
.\" 
.TH pexlsfonts 1 "$Revision: 1.5 $" "Sony Microsystems"
.SH "Name"
pexlsfonts \- 
.SH "Synopsis"
.B pexlsfonts
[\-option ...]
.SH "Description"
\fIpexlsfonts\fP is currently just a simple client application
which returns the names of fonts that can support the full range
of PEX text attributes.
.SH "Options"
\fIpexlsfonts\fP does not accept all of the standard X Toolkit
command line options. It does, however, accepts the following
options:
.sp
-display \fIdisplay_name\fP
.sp
-synchronize
.sp
-queryFont
.SH "See Also"
pexdpyinfo(1)
.SH "Bugs"
Running \fIpexlsfonts\fP -queryFont will cause 
the PEX-SI server to crash.
.SH "Author"
Erwin Hom, Sony Microsystems
