.TH SPLITWD 1
.SH "NAME"
splitwd \- Collect several text-form dictionary files into a single
file to make a <1 line / 1 word type / 1 candidate> format.
.SH "SYNOPSISS"
.B "splitwd \fItextjisho\fP ..."
.SH "DESCRIPTION"
.PP
If the file in which you registered words consists of several
subfiles, it must be converted into a proper format before the word
dictionary is created.  splitword converts such text-form dictionaries
\fItextjisho\fP to make a <1 line / 1 word type / 1 candidate> format.
The result is output to the standard output.
.SH "EXAMPLE"
.nf
% splitwd user1.t user2.t | itow
.fi
.sp
Reads text-form dictionaries user1.t and user2.t, then modifies them
into the <1 word type, 1 candidate on 1 line> format.   The contents
are converted into the Wnn textform dictionary, then output to the
standard output.
.SH "SEE ALSO"
.IP "itow(1)" 12
