/* Copyright 1991 NEC Corporation, Tokyo, Japan.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose and without fee is hereby granted,
 * provided that the above copyright notice appear in all copies and that
 * both that copyright notice and this permission notice appear in
 * supporting documentation, and that the name of NEC Corporation
 * not be used in advertising or publicity pertaining to distribution
 * of the software without specific, written prior permission.  NEC 
 * Corporation makes no representations about the suitability of this
 * software for any purpose.  It is provided "as is" without express
 * or implied warranty.
 *
 * NEC CORPORATION DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
 * INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN 
 * NO EVENT SHALL NEC CORPORATION BE LIABLE FOR ANY SPECIAL, INDIRECT OR
 * CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF 
 * USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR 
 * OTHER TORTUOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR 
 * PERFORMANCE OF THIS SOFTWARE. 
 */

static char emptymap_id[] = "@(#) 102.1 $Header: /work/nk.R3.1/lib/iroha/RCS/emptymap.c,v 3.1 91/09/02 14:03:21 kon Exp $";

extern AlphaMode(), HenkanNyuryokuMode(), ZenHiraKakuteiMode();
extern ZenKataKakuteiMode(), HanKataKakuteiMode(), ZenAlphaKakuteiMode();
extern HanAlphaKakuteiMode(), HexMode(), BushuMode(), KigoIchiran();
extern KigoIchiran(), UiUtilMode();
extern DoFuncSequence(),UseOtherKeymap();

#define NONE IROHA_FN_Undefined

static int (*empty_funcs[])() = {
/* 未定義                           */    EmptySelfInsert,
/* 自分自身を挿入する関数           */    EmptySelfInsert,
/* 修飾しながら挿入する関数         */    EmptyYomiInsert,
/* 引用挿入			    */    EmptyQuotedInsert,
/* 日本語入力モード                 */    NONE,
/* アルファベット入力モード         */    AlphaMode,
/* 変換入力モード                   */    HenkanNyuryokuMode,
/* 全角ひらがな確定入力モード       */    ZenHiraKakuteiMode,
/* 全角カタカナ確定入力モード       */    ZenKataKakuteiMode,
/* 半角カタカナ確定入力モード       */    HanKataKakuteiMode,
/* 全角アルファベット確定入力モード */    ZenAlphaKakuteiMode,
/* 半角アルファベット確定入力モード */    HanAlphaKakuteiMode,
/* １６進入力モード		    */    HexMode,
/* 部首入力モード		    */    BushuMode,
/* 記号入力モード		    */    KigoIchiran,
/* 右へ                             */    NONE,
/* 左へ                             */    NONE,
/* 次の行                           */    NONE,
/* 前の行                           */    NONE,
/* 行頭                             */    NONE,
/* 行末                             */    NONE,
/* 後ろを削除                       */    NONE,
/* 前に削除                         */    EmptyDeletePrevious,
/* 行末まで削除                     */    NONE,
/* 変換                             */    NONE,
/* 確定                             */    EmptyKakutei,
/* 伸ばし                           */    NONE,
/* 縮め                             */    NONE,
/* 文節伸縮モードへ                 */    NONE, 		   
/* 取りやめ                         */    EmptyQuit,
/* 拡張モード                       */    UiUtilMode,
/* １６進コードとして変換           */    NONE,
/* 部首名として変換                 */    NONE,
/* 候補一覧                         */    NONE,
/* 部分無変換                       */    NONE,
/* 全角への変換                     */    NONE,
/* 半角への変換                     */    NONE,
/* 大文字への変換                   */    NONE,
/* キャピタライズ                   */    NONE,
/* 小文字への変換                   */    NONE,
/* ひらがな変換			    */	  NONE,
/* カタカナ変換			    */	  NONE,
/* ローマ字変換			    */	  NONE,
/* 複数のキーの割り当て             */    DoFuncSequence,
/* キーシーケンスへの対応           */    UseOtherKeymap,
};

unsigned char empty_kmap[256] =
{               
/* C-@ */       IROHA_FN_SelfInsert,
/* C-a */       IROHA_FN_SelfInsert,
/* C-b */       IROHA_FN_SelfInsert,
/* C-c */       IROHA_FN_SelfInsert,
/* C-d */       IROHA_FN_SelfInsert,
/* C-e */       IROHA_FN_SelfInsert,
/* C-f */       IROHA_FN_SelfInsert,
/* C-g */       IROHA_FN_Quit,
/* C-h */       IROHA_FN_DeletePrevious,
/* C-i */       IROHA_FN_SelfInsert,
/* C-j */       IROHA_FN_Kakutei,
/* C-k */       IROHA_FN_SelfInsert,
/* C-l */       IROHA_FN_SelfInsert,
/* C-m */       IROHA_FN_Kakutei,
/* C-n */       IROHA_FN_SelfInsert,
/* C-o */       IROHA_FN_AlphaMode,
/* C-p */       IROHA_FN_SelfInsert,
/* C-q */       IROHA_FN_QuotedInsert,
/* C-r */       IROHA_FN_SelfInsert,
/* C-s */       IROHA_FN_SelfInsert,
/* C-t */       IROHA_FN_SelfInsert,
/* C-u */       IROHA_FN_SelfInsert,
/* C-v */       IROHA_FN_SelfInsert,
/* C-w */       IROHA_FN_SelfInsert,
/* C-x */       IROHA_FN_SelfInsert,
/* C-y */       IROHA_FN_SelfInsert,
/* C-z */       IROHA_FN_SelfInsert,
/* C-[ */       IROHA_FN_SelfInsert,
/* C-\ */       IROHA_FN_SelfInsert,
/* C-] */       IROHA_FN_SelfInsert,
/* C-^ */       IROHA_FN_SelfInsert,
/* C-_ */       IROHA_FN_SelfInsert,
/* space */     IROHA_FN_SelfInsert,
/* ! */         IROHA_FN_FunctionalInsert,
/* " */         IROHA_FN_FunctionalInsert,
/* # */         IROHA_FN_FunctionalInsert,
/* $ */         IROHA_FN_FunctionalInsert,
/* % */         IROHA_FN_FunctionalInsert,
/* & */         IROHA_FN_FunctionalInsert,
/* ' */         IROHA_FN_FunctionalInsert,
/* ( */         IROHA_FN_FunctionalInsert,
/* ) */         IROHA_FN_FunctionalInsert,
/* * */         IROHA_FN_FunctionalInsert,
/* + */         IROHA_FN_FunctionalInsert,
/* , */         IROHA_FN_FunctionalInsert,
/* - */         IROHA_FN_FunctionalInsert,
/* . */         IROHA_FN_FunctionalInsert,
/* / */         IROHA_FN_FunctionalInsert,
/* 0 */         IROHA_FN_FunctionalInsert,
/* 1 */         IROHA_FN_FunctionalInsert,
/* 2 */         IROHA_FN_FunctionalInsert,
/* 3 */         IROHA_FN_FunctionalInsert,
/* 4 */         IROHA_FN_FunctionalInsert,
/* 5 */         IROHA_FN_FunctionalInsert,
/* 6 */         IROHA_FN_FunctionalInsert,
/* 7 */         IROHA_FN_FunctionalInsert,
/* 8 */         IROHA_FN_FunctionalInsert,
/* 9 */         IROHA_FN_FunctionalInsert,
/*   : */       IROHA_FN_FunctionalInsert,
/* ; */         IROHA_FN_FunctionalInsert,
/* < */         IROHA_FN_FunctionalInsert,
/* = */         IROHA_FN_FunctionalInsert,
/* > */         IROHA_FN_FunctionalInsert,
/* ? */         IROHA_FN_FunctionalInsert,
/* @ */         IROHA_FN_FunctionalInsert,
/* A */         IROHA_FN_FunctionalInsert,
/* B */         IROHA_FN_FunctionalInsert,
/* C */         IROHA_FN_FunctionalInsert,
/* D */         IROHA_FN_FunctionalInsert,
/* E */         IROHA_FN_FunctionalInsert,
/* F */         IROHA_FN_FunctionalInsert,
/* G */         IROHA_FN_FunctionalInsert,
/* H */         IROHA_FN_FunctionalInsert,
/* I */         IROHA_FN_FunctionalInsert,
/* J */         IROHA_FN_FunctionalInsert,
/* K */         IROHA_FN_FunctionalInsert,
/* L */         IROHA_FN_FunctionalInsert,
/* M */         IROHA_FN_FunctionalInsert,
/* N */         IROHA_FN_FunctionalInsert,
/* O */         IROHA_FN_FunctionalInsert,
/* P */         IROHA_FN_FunctionalInsert,
/* Q */         IROHA_FN_FunctionalInsert,
/* R */         IROHA_FN_FunctionalInsert,
/* S */         IROHA_FN_FunctionalInsert,
/* T */         IROHA_FN_FunctionalInsert,
/* U */         IROHA_FN_FunctionalInsert,
/* V */         IROHA_FN_FunctionalInsert,
/* W */         IROHA_FN_FunctionalInsert,
/* X */         IROHA_FN_FunctionalInsert,
/* Y */         IROHA_FN_FunctionalInsert,
/* Z */         IROHA_FN_FunctionalInsert,
/* [ */         IROHA_FN_FunctionalInsert,
/* \ */         IROHA_FN_FunctionalInsert,
/* ] */         IROHA_FN_FunctionalInsert,
/* ^ */         IROHA_FN_FunctionalInsert,
/* _ */         IROHA_FN_FunctionalInsert,
/* ` */         IROHA_FN_FunctionalInsert,
/* a */         IROHA_FN_FunctionalInsert,
/* b */         IROHA_FN_FunctionalInsert,
/* c */         IROHA_FN_FunctionalInsert,
/* d */         IROHA_FN_FunctionalInsert,
/* e */         IROHA_FN_FunctionalInsert,
/* f */         IROHA_FN_FunctionalInsert,
/* g */         IROHA_FN_FunctionalInsert,
/* h */         IROHA_FN_FunctionalInsert,
/* i */         IROHA_FN_FunctionalInsert,
/* j */         IROHA_FN_FunctionalInsert,
/* k */         IROHA_FN_FunctionalInsert,
/* l */         IROHA_FN_FunctionalInsert,
/* m */         IROHA_FN_FunctionalInsert,
/* n */         IROHA_FN_FunctionalInsert,
/* o */         IROHA_FN_FunctionalInsert,
/* p */         IROHA_FN_FunctionalInsert,
/* q */         IROHA_FN_FunctionalInsert,
/* r */         IROHA_FN_FunctionalInsert,
/* s */         IROHA_FN_FunctionalInsert,
/* t */         IROHA_FN_FunctionalInsert,
/* u */         IROHA_FN_FunctionalInsert,
/* v */         IROHA_FN_FunctionalInsert,
/* w */         IROHA_FN_FunctionalInsert,
/* x */         IROHA_FN_FunctionalInsert,
/* y */         IROHA_FN_FunctionalInsert,
/* z */         IROHA_FN_FunctionalInsert,
/* { */         IROHA_FN_FunctionalInsert,
/* | */         IROHA_FN_FunctionalInsert,
/* } */         IROHA_FN_FunctionalInsert,
/* ~ */         IROHA_FN_FunctionalInsert,
/* DEL */       IROHA_FN_SelfInsert,
/* Nfer */      NONE,
/* Xfer */      IROHA_FN_AlphaMode,
/* Up */        NONE,
/* Left */      NONE,
/* Right */     NONE,
/* Down */      NONE,
/* Insert */    IROHA_FN_KigouMode,
/* Rollup */    NONE,
/* Rolldown */  NONE,
/* Home */      NONE,
/* Help */      IROHA_FN_ExtendMode,
/* KeyPad */    NONE,
/* 8c */        NONE,
/* 8d */        NONE,
/* 8e */        NONE,
/* 8f */        NONE,
/* S-nfer */    NONE,
/* S-xfer */    IROHA_FN_AlphaMode,
/* S-up */      NONE,
/* S-left */    NONE,
/* S-right */   NONE,
/* S-down */    NONE,
/* C-nfer */    NONE,
/* C-xfer */    IROHA_FN_AlphaMode,
/* C-up */      NONE,
/* C-left */    NONE,
/* C-right */   NONE,
/* C-down */    NONE,
/* 9c */        NONE,
/* 9d */        NONE,
/* 9e */        NONE,
/* 9f */        NONE,
/* KANASPACE */ NONE,
/* 。 */        IROHA_FN_FunctionalInsert,
/* 「 */        IROHA_FN_FunctionalInsert,
/* 」 */        IROHA_FN_FunctionalInsert,
/* 、 */        IROHA_FN_FunctionalInsert,
/* ・ */        IROHA_FN_FunctionalInsert,
/* ヲ */        IROHA_FN_FunctionalInsert,
/* ァ */        IROHA_FN_FunctionalInsert,
/* ィ */        IROHA_FN_FunctionalInsert,
/* ゥ */        IROHA_FN_FunctionalInsert,
/* ェ */        IROHA_FN_FunctionalInsert,
/* ォ */        IROHA_FN_FunctionalInsert,
/* ャ */        IROHA_FN_FunctionalInsert,
/* ュ */        IROHA_FN_FunctionalInsert,
/* ョ */        IROHA_FN_FunctionalInsert,
/* ッ */        IROHA_FN_FunctionalInsert,
/* ー */        IROHA_FN_FunctionalInsert,
/* ア */        IROHA_FN_FunctionalInsert,
/* イ */        IROHA_FN_FunctionalInsert,
/* ウ */        IROHA_FN_FunctionalInsert,
/* エ */        IROHA_FN_FunctionalInsert,
/* オ */        IROHA_FN_FunctionalInsert,
/* カ */        IROHA_FN_FunctionalInsert,
/* キ */        IROHA_FN_FunctionalInsert,
/* ク */        IROHA_FN_FunctionalInsert,
/* ケ */        IROHA_FN_FunctionalInsert,
/* コ */        IROHA_FN_FunctionalInsert,
/* サ */        IROHA_FN_FunctionalInsert,
/* シ */        IROHA_FN_FunctionalInsert,
/* ス */        IROHA_FN_FunctionalInsert,
/* セ */        IROHA_FN_FunctionalInsert,
/* ソ */        IROHA_FN_FunctionalInsert,
/* タ */        IROHA_FN_FunctionalInsert,
/* チ */        IROHA_FN_FunctionalInsert,
/* ツ */        IROHA_FN_FunctionalInsert,
/* テ */        IROHA_FN_FunctionalInsert,
/* ト */        IROHA_FN_FunctionalInsert,
/* ナ */        IROHA_FN_FunctionalInsert,
/* ニ */        IROHA_FN_FunctionalInsert,
/* ヌ */        IROHA_FN_FunctionalInsert,
/* ネ */        IROHA_FN_FunctionalInsert,
/* ノ */        IROHA_FN_FunctionalInsert,
/* ハ */        IROHA_FN_FunctionalInsert,
/* ヒ */        IROHA_FN_FunctionalInsert,
/* フ */        IROHA_FN_FunctionalInsert,
/* ヘ */        IROHA_FN_FunctionalInsert,
/* ホ */        IROHA_FN_FunctionalInsert,
/* マ */        IROHA_FN_FunctionalInsert,
/* ミ */        IROHA_FN_FunctionalInsert,
/* ム */        IROHA_FN_FunctionalInsert,
/* メ */        IROHA_FN_FunctionalInsert,
/* モ */        IROHA_FN_FunctionalInsert,
/* ヤ */        IROHA_FN_FunctionalInsert,
/* ユ */        IROHA_FN_FunctionalInsert,
/* ヨ */        IROHA_FN_FunctionalInsert,
/* ラ */        IROHA_FN_FunctionalInsert,
/* リ */        IROHA_FN_FunctionalInsert,
/* ル */        IROHA_FN_FunctionalInsert,
/* レ */        IROHA_FN_FunctionalInsert,
/* ロ */        IROHA_FN_FunctionalInsert,
/* ワ */        IROHA_FN_FunctionalInsert,
/* ン */        IROHA_FN_FunctionalInsert,
/* ゛ */        IROHA_FN_FunctionalInsert,
/* ゜ */        IROHA_FN_FunctionalInsert,
/* F1 */        NONE,
/* F2 */        NONE,
/* F3 */        NONE,
/* F4 */        NONE,
/* F5 */        NONE,
/* F6 */        NONE,
/* F7 */        NONE,
/* F8 */        NONE,
/* F9 */        NONE,
/* F10 */       NONE,
/* ea */        NONE,
/* eb */        NONE,
/* ec */        NONE,
/* ed */        NONE,
/* ee */        NONE,
/* ef */        NONE,
/* PF1 */       NONE,
/* PF2 */       NONE,
/* PF3 */       NONE,
/* PF4 */       NONE,
/* PF5 */       NONE,
/* PF6 */       NONE,
/* PF7 */       NONE,
/* PF8 */       NONE,
/* PF9 */       NONE,
/* PF10 */      NONE,
/* fa */        NONE,
/* fb */        NONE,
/* fc */        NONE,
/* fd */        NONE,
/* fe */        NONE,
/* ff */        NONE,
};

KanjiModeRec empty_mode = {
  simplefunc,
  empty_kmap,
  IROHA_KANJIMODE_TABLE_SHARED | IROHA_KANJIMODE_EMPTY_MODE,
  empty_funcs,
};

