/* $XConsortium: pm_ui.h,v 5.1 91/02/16 09:32:56 rws Exp $ */

/***********************************************************
Copyright (c) 1989-1991 by Sun Microsystems, Inc. and the X Consortium.

                        All Rights Reserved

Permission to use, copy, modify, and distribute this software and its 
documentation for any purpose and without fee is hereby granted, 
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in 
supporting documentation, and that the names of Sun Microsystems,
the X Consortium, and MIT not be used in advertising or publicity 
pertaining to distribution of the software without specific, written 
prior permission.  

SUN MICROSYSTEMS DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, 
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT 
SHALL SUN MICROSYSTEMS BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL 
DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
SOFTWARE.

******************************************************************/

#ifndef	pm_HEADER
#define	pm_HEADER

/*
 * pm_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `pm.G'.
 * DO NOT EDIT BY HAND.
 */

extern int	INSTANCE;
extern Xv_opaque	pm_view_menu_create();

extern Xv_opaque	pm_edit_menu_create();

extern Xv_opaque	pm_props_menu_create();

typedef struct {
	Xv_opaque	pyr_frame;
	Xv_opaque	main_panel;
	Xv_opaque	obj_button;
	Xv_opaque	view_button;
	Xv_opaque	props_button;
	Xv_opaque	canvas;
} pm_pyr_frame_objects;
extern pm_pyr_frame_objects	*pm_pyr_frame_objects_initialize();
extern Xv_opaque	pm_pyr_frame_pyr_frame_create();

extern Xv_opaque	pm_pyr_frame_main_panel_create();

extern Xv_opaque	pm_pyr_frame_obj_button_create();

extern Xv_opaque	pm_pyr_frame_view_button_create();

extern Xv_opaque	pm_pyr_frame_props_button_create();

extern Xv_opaque	pm_pyr_frame_canvas_create();

typedef struct {
	Xv_opaque	rot_panel_frame;
	Xv_opaque	rot_panel;
	Xv_opaque	pn_x_rotation;
	Xv_opaque	pn_y_rotation;
	Xv_opaque	pn_z_rotation;
	Xv_opaque	pn_scale;
	Xv_opaque	pn_auto_rotate_toggle;
} pm_rot_panel_frame_objects;
extern pm_rot_panel_frame_objects	*pm_rot_panel_frame_objects_initialize();
extern Xv_opaque	pm_rot_panel_frame_rot_panel_frame_create();

extern Xv_opaque	pm_rot_panel_frame_rot_panel_create();

extern Xv_opaque	pm_rot_panel_frame_pn_x_rotation_create();

extern Xv_opaque	pm_rot_panel_frame_pn_y_rotation_create();

extern Xv_opaque	pm_rot_panel_frame_pn_z_rotation_create();

extern Xv_opaque	pm_rot_panel_frame_pn_scale_create();

extern Xv_opaque	pm_rot_panel_frame_pn_auto_rotate_toggle_create();

typedef struct {
	Xv_opaque	prop_panel_frame;
	Xv_opaque	prop_panel;
	Xv_opaque	ambcoef_item;
	Xv_opaque	diffcoef_item;
	Xv_opaque	speccoef_item;
	Xv_opaque	specexp_item;
	Xv_opaque	transpar_item;
	Xv_opaque	msg1;
	Xv_opaque	diffcolr_item;
	Xv_opaque	diffcolg_item;
	Xv_opaque	diffcolb_item;
	Xv_opaque	msg2;
	Xv_opaque	speccolr_item;
	Xv_opaque	speccolg_item;
	Xv_opaque	speccolb_item;
} pm_prop_panel_frame_objects;
extern pm_prop_panel_frame_objects	*pm_prop_panel_frame_objects_initialize();
extern Xv_opaque	pm_prop_panel_frame_prop_panel_frame_create();

extern Xv_opaque	pm_prop_panel_frame_prop_panel_create();

extern Xv_opaque	pm_prop_panel_frame_ambcoef_item_create();

extern Xv_opaque	pm_prop_panel_frame_diffcoef_item_create();

extern Xv_opaque	pm_prop_panel_frame_speccoef_item_create();

extern Xv_opaque	pm_prop_panel_frame_specexp_item_create();

extern Xv_opaque	pm_prop_panel_frame_transpar_item_create();

extern Xv_opaque	pm_prop_panel_frame_msg1_create();

extern Xv_opaque	pm_prop_panel_frame_diffcolr_item_create();

extern Xv_opaque	pm_prop_panel_frame_diffcolg_item_create();

extern Xv_opaque	pm_prop_panel_frame_diffcolb_item_create();

extern Xv_opaque	pm_prop_panel_frame_msg2_create();

extern Xv_opaque	pm_prop_panel_frame_speccolr_item_create();

extern Xv_opaque	pm_prop_panel_frame_speccolg_item_create();

extern Xv_opaque	pm_prop_panel_frame_speccolb_item_create();

typedef struct {
	Xv_opaque	light_panel_frame;
	Xv_opaque	light_panel;
	Xv_opaque	lnum_item;
	Xv_opaque	lonoff_item;
	Xv_opaque	ltype_item;
	Xv_opaque	message4;
	Xv_opaque	lcolr_item;
	Xv_opaque	lcolg_item;
	Xv_opaque	lcolb_item;
	Xv_opaque	ldir_item;
	Xv_opaque	ldirx_item;
	Xv_opaque	ldiry_item;
	Xv_opaque	ldirz_item;
	Xv_opaque	lpos_item;
	Xv_opaque	latten_item;
	Xv_opaque	lexp_item;
	Xv_opaque	lspread_item;
	Xv_opaque	labutton;
	Xv_opaque	lrbutton;
} pm_light_panel_frame_objects;
extern pm_light_panel_frame_objects	*pm_light_panel_frame_objects_initialize();
extern Xv_opaque	pm_light_panel_frame_light_panel_frame_create();

extern Xv_opaque	pm_light_panel_frame_light_panel_create();

extern Xv_opaque	pm_light_panel_frame_lnum_item_create();

extern Xv_opaque	pm_light_panel_frame_lonoff_item_create();

extern Xv_opaque	pm_light_panel_frame_ltype_item_create();

extern Xv_opaque	pm_light_panel_frame_message4_create();

extern Xv_opaque	pm_light_panel_frame_lcolr_item_create();

extern Xv_opaque	pm_light_panel_frame_lcolg_item_create();

extern Xv_opaque	pm_light_panel_frame_lcolb_item_create();

extern Xv_opaque	pm_light_panel_frame_ldir_item_create();

extern Xv_opaque	pm_light_panel_frame_ldirx_item_create();

extern Xv_opaque	pm_light_panel_frame_ldiry_item_create();

extern Xv_opaque	pm_light_panel_frame_ldirz_item_create();

extern Xv_opaque	pm_light_panel_frame_lpos_item_create();

extern Xv_opaque	pm_light_panel_frame_latten_item_create();

extern Xv_opaque	pm_light_panel_frame_lexp_item_create();

extern Xv_opaque	pm_light_panel_frame_lspread_item_create();

extern Xv_opaque	pm_light_panel_frame_labutton_create();

extern Xv_opaque	pm_light_panel_frame_lrbutton_create();

typedef struct {
	Xv_opaque	orient_panel_frame;
	Xv_opaque	vieworient_panel;
	Xv_opaque	message1;
	Xv_opaque	pn_vpn_x;
	Xv_opaque	pn_vpn_y;
	Xv_opaque	pn_vpn_z;
	Xv_opaque	message2;
	Xv_opaque	pn_vup_x;
	Xv_opaque	pn_vup_y;
	Xv_opaque	pn_vup_z;
	Xv_opaque	message3;
	Xv_opaque	pn_vrp_x;
	Xv_opaque	pn_vrp_y;
	Xv_opaque	pn_vrp_z;
} pm_orient_panel_frame_objects;
extern pm_orient_panel_frame_objects	*pm_orient_panel_frame_objects_initialize();
extern Xv_opaque	pm_orient_panel_frame_orient_panel_frame_create();

extern Xv_opaque	pm_orient_panel_frame_vieworient_panel_create();

extern Xv_opaque	pm_orient_panel_frame_message1_create();

extern Xv_opaque	pm_orient_panel_frame_pn_vpn_x_create();

extern Xv_opaque	pm_orient_panel_frame_pn_vpn_y_create();

extern Xv_opaque	pm_orient_panel_frame_pn_vpn_z_create();

extern Xv_opaque	pm_orient_panel_frame_message2_create();

extern Xv_opaque	pm_orient_panel_frame_pn_vup_x_create();

extern Xv_opaque	pm_orient_panel_frame_pn_vup_y_create();

extern Xv_opaque	pm_orient_panel_frame_pn_vup_z_create();

extern Xv_opaque	pm_orient_panel_frame_message3_create();

extern Xv_opaque	pm_orient_panel_frame_pn_vrp_x_create();

extern Xv_opaque	pm_orient_panel_frame_pn_vrp_y_create();

extern Xv_opaque	pm_orient_panel_frame_pn_vrp_z_create();

typedef struct {
	Xv_opaque	viewmap_panel_frame;
	Xv_opaque	viewmap_panel;
	Xv_opaque	message5;
	Xv_opaque	pn_win_xmin;
	Xv_opaque	pn_win_xmax;
	Xv_opaque	pn_win_ymin;
	Xv_opaque	pn_win_ymax;
	Xv_opaque	message6;
	Xv_opaque	pn_viewp_xmin;
	Xv_opaque	pn_viewp_xmax;
	Xv_opaque	pn_viewp_ymin;
	Xv_opaque	pn_viewp_ymax;
	Xv_opaque	pn_viewp_zmin;
	Xv_opaque	pn_viewp_zmax;
	Xv_opaque	message7;
	Xv_opaque	pn_prp_x;
	Xv_opaque	pn_prp_y;
	Xv_opaque	pn_prp_z;
	Xv_opaque	pn_proj_type;
	Xv_opaque	message8;
	Xv_opaque	pn_pln_front;
	Xv_opaque	pn_pln_back;
	Xv_opaque	pn_pln_view;
} pm_viewmap_panel_frame_objects;
extern pm_viewmap_panel_frame_objects	*pm_viewmap_panel_frame_objects_initialize();
extern Xv_opaque	pm_viewmap_panel_frame_viewmap_panel_frame_create();

extern Xv_opaque	pm_viewmap_panel_frame_viewmap_panel_create();

extern Xv_opaque	pm_viewmap_panel_frame_message5_create();

extern Xv_opaque	pm_viewmap_panel_frame_pn_win_xmin_create();

extern Xv_opaque	pm_viewmap_panel_frame_pn_win_xmax_create();

extern Xv_opaque	pm_viewmap_panel_frame_pn_win_ymin_create();

extern Xv_opaque	pm_viewmap_panel_frame_pn_win_ymax_create();

extern Xv_opaque	pm_viewmap_panel_frame_message6_create();

extern Xv_opaque	pm_viewmap_panel_frame_pn_viewp_xmin_create();

extern Xv_opaque	pm_viewmap_panel_frame_pn_viewp_xmax_create();

extern Xv_opaque	pm_viewmap_panel_frame_pn_viewp_ymin_create();

extern Xv_opaque	pm_viewmap_panel_frame_pn_viewp_ymax_create();

extern Xv_opaque	pm_viewmap_panel_frame_pn_viewp_zmin_create();

extern Xv_opaque	pm_viewmap_panel_frame_pn_viewp_zmax_create();

extern Xv_opaque	pm_viewmap_panel_frame_message7_create();

extern Xv_opaque	pm_viewmap_panel_frame_pn_prp_x_create();

extern Xv_opaque	pm_viewmap_panel_frame_pn_prp_y_create();

extern Xv_opaque	pm_viewmap_panel_frame_pn_prp_z_create();

extern Xv_opaque	pm_viewmap_panel_frame_pn_proj_type_create();

extern Xv_opaque	pm_viewmap_panel_frame_message8_create();

extern Xv_opaque	pm_viewmap_panel_frame_pn_pln_front_create();

extern Xv_opaque	pm_viewmap_panel_frame_pn_pln_back_create();

extern Xv_opaque	pm_viewmap_panel_frame_pn_pln_view_create();

typedef struct {
	Xv_opaque	object_panel_frame;
	Xv_opaque	object_panel;
	Xv_opaque	pn_pyr_type;
	Xv_opaque	pn_pyr_depth;
	Xv_opaque	pn_pyr_children;
	Xv_opaque	pn_pyr_random;
	Xv_opaque	pn_pyr_probability;
	Xv_opaque	pn_build_button;
	Xv_opaque	pn_pyr_reset;
	Xv_opaque	pn_cube_row0;
	Xv_opaque	pn_cube_row1;
	Xv_opaque	pn_cube_row2;
} pm_object_panel_frame_objects;
extern pm_object_panel_frame_objects	*pm_object_panel_frame_objects_initialize();
extern Xv_opaque	pm_object_panel_frame_object_panel_frame_create();

extern Xv_opaque	pm_object_panel_frame_object_panel_create();

extern Xv_opaque	pm_object_panel_frame_pn_pyr_type_create();

extern Xv_opaque	pm_object_panel_frame_pn_pyr_depth_create();

extern Xv_opaque	pm_object_panel_frame_pn_pyr_children_create();

extern Xv_opaque	pm_object_panel_frame_pn_pyr_random_create();

extern Xv_opaque	pm_object_panel_frame_pn_pyr_probability_create();

extern Xv_opaque	pm_object_panel_frame_pn_build_button_create();

extern Xv_opaque	pm_object_panel_frame_pn_pyr_reset_create();

extern Xv_opaque	pm_object_panel_frame_pn_cube_row0_create();

extern Xv_opaque	pm_object_panel_frame_pn_cube_row1_create();

extern Xv_opaque	pm_object_panel_frame_pn_cube_row2_create();

typedef struct {
	Xv_opaque	light_sources_frame;
} pm_light_sources_frame_objects;
extern pm_light_sources_frame_objects	*pm_light_sources_frame_objects_initialize();
extern Xv_opaque	pm_light_sources_frame_light_sources_frame_create();

#endif
